playlists:
 chicago-riot-fest-2016:
   slug: chicago-riot-fest-2016
   name: Chicago Riot Fest 2016
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL the weekend of September 16th through 18th 2016.
             {{ playlist_title }} will feature headliners of <em>The original Misfits</em>, <em>Ween</em>, <em>Death Cab for Cutie</em>, <em>Rob Zombie</em>, <em>Social Distortion</em>, and <em>Brand New</em>.
          </p>
          <p>
            <b>Update (May 23, 2016)</b>: Morrissey announces that he will no longer be performing at {{ playlist_title }}.  This comes five days after Riot Fest announced that Morrissey will be part of the {{ playlist_title }} lineup.
          </p>
   image: /images/playlists/chicago-riot-fest-2015-sunday.png
   spotify_uri: spotify:user:easander:playlist:02M8yjDiPAbfQzcTiJlQ8P
 coachella-2016-friday:
   slug: coachella-2016-friday
   name: Coachella 2016 Friday
   content: >
          <p>
             <a href="https://www.coachella.com/home/" target="_blank">{{ playlist_title }}</a> will be held Fridays, April 15th and 22nd 2016 in India, California at the Empire Polo Grounds.
             {{ playlist_title }} will feature headliners of <em>Years &amp; Years</em>, <em>Volbeat</em>, <em>Unknown Mortal Orchestra</em>, and <em>Underworld</em>.
          </p>
          <p>
             In 1999 Paul Tollett founded Coachella and features many genres of music, including rock, indie, hip hop, and electronic dance music.
             Across the grounds, several stages continuously host live music.  View the <a href="https://www.coachella.com/lineup/" target="_blank">{{ playlist_title }} full lineup</a>
             at Coachella's website.
          </p>
   image: /images/playlists/coachella-2016-friday.jpg
   spotify_uri: spotify:user:easander:playlist:6NMNfWJwtc5yCRgKu1j37A
 rock-on-the-range-2016:
   slug: rock-on-the-range-2016
   name: Rock on the Range 2016
   content: >
          <p>
            <a href="http://rockontherange.com/index.html" target="_blank">{{ playlist_title }}</a> is the tenth
            anniversary of Rock on the Range.  {{ playlist_title }} will be the weekend of May 20 - 22, 2016 at
            the <a
            href="https://www.google.com/maps/dir//MAPFRE+Stadium,+One+Black+%26+Gold+Blvd,+Columbus,+OH+43211/@40.0090861,-82.9934167,17z/data=!4m13!1m4!3m3!1s0x883889536d498093:0x2b5cb386c60ffb9f!2sMAPFRE+Stadium!3b1!4m7!1m0!1m5!1m1!1s0x883889536d498093:0x2b5cb386c60ffb9f!2m2!1d-82.991228!2d40.009082" target="_blank">MAPFRE Stadium</a>
            (One Black & Gold Boulevard Columbus, Ohio 43211). Rock on the Range isn't holding anything back
            for their tenth anniversary as they will be featuring 56 bands during the three day span.
          </p>
          <p>
            Headlining this years show will be <em>Red Hot Chili Peppers</em>, <em>Disturbed</em>, and <em>Rob Zombie</em>.
            Other featured acts performing include <em>Megadeth</em>, <em>Death From Above 1979</em>, <em>Five Finger
            Death Punch</em>, and the always fun <em>Steel Panther</em>!  <a
            href="http://rockontherange.com/tickets_weekend.html" target="_blank">Go
            get your tickets</a> while you still can.
          </p>
   image: /images/playlists/rock-on-the-range-2016.jpg
   spotify_uri: spotify:user:easander:playlist:5p89Maiw94Vkxf8kkdRYbg
 chicago-jazz-festival-2015:
   slug: chicago-jazz-festival-2015
   name: Chicago Jazz Festival 2015
   content: >
          <p>
            <a href="http://www.cityofchicago.org/city/en/depts/dca/supp_info/chicago_jazz_festival.html" target="_blank">{{ playlist_title }}</a> is a FREE jazz festival that will be held in Chicago, IL.  It will
            take place Labor Day weekend September 3 - 6, 2015 at the Chicago Cultural Center and Millennium Park (Jay Pritzker Pavilion).  The Chicago Jazz Festival has been demonstrating the wide array of talents
            in the jazz community since 1979.
          </p>
   image: /images/playlists/chicago-jazz-festival-2015.jpg
   spotify_uri: spotify:user:easander:playlist:4iLPlfkzb77Vs3kMwUUQ4K
 seattle-bumbershoot-2015-sunday:
   slug: seattle-bumbershoot-2015-sunday
   name: Seattle Bumbershoot 2015 Sunday
   content: >
          <p>
             <a href="http://bumbershoot.com/full_lineup" target="_blank">{{ playlist_title }}</a> will be held Sunday, September 6th 2015 in Seattle, Washington.  {{ playlist_title }} will feature headliners of <em>Faith No More</em>, <em>Zedd</em>,
             <em>Social Distortion</em>, and <em>Brand New</em>.
          </p>
          <p>
             <a href="http://bumbershoot.com/home" target="_blank">Bumbershoot</a> is an annual international music and arts festival held in Seattle, Washington. One of North America's largest such festivals,
             it takes place every Labor Day weekend at the 74-acre Seattle Center, which was built for the 1962 World's Fair. Seattle Center includes both indoor theaters and outdoor stages.
          </p>
   image: /images/playlists/seattle-bumbershoot-2015-sunday.jpg
   spotify_uri: spotify:user:easander:playlist:0itlK0bKwaqQfUwr23a8h9
 seattle-bumbershoot-2015-saturday:
   slug: seattle-bumbershoot-2015-saturday
   name: Seattle Bumbershoot 2015 Saturday
   content: >
          <p>
             <a href="http://bumbershoot.com/full_lineup" target="_blank">{{ playlist_title }}</a> will be held Saturday, September 5th 2015 in Seattle, Washington.  {{ playlist_title }} will feature headliners of <em>The Weeknd</em>, <em>Chance The Rapper</em>,
             <em>Cake</em>, and <em>Fitz and The Tantrums</em>.
          </p>
          <p>
             <a href="http://bumbershoot.com/home" target="_blank">Bumbershoot</a> is an annual international music and arts festival held in Seattle, Washington. One of North America's largest such festivals,
             it takes place every Labor Day weekend at the 74-acre Seattle Center, which was built for the 1962 World's Fair. Seattle Center includes both indoor theaters and outdoor stages.
          </p>
   image: /images/playlists/seattle-bumbershoot-2015-saturday.png
   spotify_uri: spotify:user:easander:playlist:7rSgqQlx6KJ6xDCISKjpG3
 chicago-riot-fest-2015-sunday:
   slug: chicago-riot-fest-2015-sunday
   name: Chicago Riot Fest 2015 Sunday
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL on September 13th 2015.
             {{ playlist_title }} will feature headliners of <em>Modest Mouse</em>, <em>The Prodigy</em>, <em>Snoop Dogg</em>, <em>Damian Marley</em>, and <em>Tenacious D</em>.
          </p>
   image: /images/playlists/chicago-riot-fest-2015-sunday.png
   spotify_uri: spotify:user:easander:playlist:13jQdWiVBi1NEh1cVCpLJD
 chicago-riot-fest-2015-saturday:
   slug: chicago-riot-fest-2015-saturday
   name: Chicago Riot Fest 2015 Saturday
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL on September 12th 2015.
             {{ playlist_title }} will feature headliners of <em>System of a Down</em>, <em>Iggy Pop</em>, <em>Rancid</em>, <em>Billy Idol</em>, and <em>Taking Back Sunday</em>.
          </p>
   image: /images/playlists/chicago-riot-fest-2015-saturday.jpg
   spotify_uri: spotify:user:easander:playlist:5NWiMHiGdNOyMX4KqMs2Z8
 chicago-riot-fest-2015-friday:
   slug: chicago-riot-fest-2015-friday
   name: Chicago Riot Fest 2015 Friday
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL on September 11th 2015.
             {{ playlist_title }} will feature headliners of <em>No Doubt</em>, <em>Faith No More</em>, <em>Motörhead</em>, <em>Ice Cube</em>, and <em>Alkaline Trio</em>.
          </p>
   image: /images/playlists/chicago-riot-fest-2015-friday.jpg
   spotify_uri: spotify:user:easander:playlist:7BDifAdjeF0sEJbkEgKrI6
 denver-riot-fest-and-rodeo-2015:
   slug: denver-riot-fest-and-rodeo-2015
   name: Denver Riot Fest and Rodeo 2015
   content: >
          <p>
             <a href="http://riotfest.org/denver/" target="_blank">{{ playlist_title }}</a> will be held at National Western Complex (4655 Humboldt St, Denver CO) the weekend of August 28th, 29th, and 30th 2015.
             {{ playlist_title }} will feature headliners of <em>System of a Down</em>, <em>Iggy Pop</em>, <em>Modest Mouse</em>, <em>Pixies</em>, <em>The Prodigy</em>, and <em>Snoop Dogg</em>.
          </p>
   image: /images/playlists/denver-riot-fest-2015.jpg
   spotify_uri: spotify:user:easander:playlist:3oTi3mzcodmZoE8yLsLbLk
 toronto-riot-fest-2015:
   slug: toronto-riot-fest-2015
   name: Toronto Riot Fest 2015
   content: >
          <p>
             <a href="http://riotfest.org/toronto/" target="_blank">{{ playlist_title }}</a> will be held in Downsview Park (35 Carl Hall Rd) Toronto, ON September 19th and 20th 2015.
             {{ playlist_title }} will feature headliners of <em>Alexisonfire</em>, <em>Weezer</em> (playing Pinkerton and the Blue Album), <em>The Prodigy</em>, and <em>Wu-Tang Clan</em>.
             <em>Rancid</em> will also be playing ...And Out Come The Wolves.
          </p>
   image: /images/playlists/toronto-riot-fest-2015.jpg
   spotify_uri: spotify:user:easander:playlist:4rGvL29N07RVrgKCVU5akZ
 chicago-riot-fest-2015:
   slug: chicago-riot-fest-2015
   name: Chicago Riot Fest 2015
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL the weekend of September 11-13 2015.
             {{ playlist_title }} will feature headliners of <em>No Doubt</em>, <em>System of a Down</em>, <em>Modest Mouse</em>, <em>Faith No More</em>, and <em>The Prodigy</em>.
             <em>Rancid</em> will also be playing ...And Out Come The Wolves in its entirety.
             <br /><br />
             <em>Update: System of a Down, The Prodigy, 88 Fingers Louie, and Chef'special added to Riot Fest 2015!</em>
          </p>
   image: /images/playlists/chicago-riot-fest-2015.jpg
   spotify_uri: spotify:user:easander:playlist:3jxmUYBHHYuZEyAaXKF76K
 chicago-riot-fest-2014:
   slug: chicago-riot-fest-2014
   name: Chicago Riot Fest 2014
   content: ''
   image: /images/playlists/chicago-riot-fest-2014.jpg
   spotify_uri: spotify:user:easander:playlist:3fl2SYC95YZL9Lsmm3bXl4
 summerland-tour-2014:
   slug: summerland-tour-2014
   name: Summerland Tour 2014
   content: ''
   image: /images/playlists/summerland-tour-2014.jpg
   spotify_uri: spotify:user:easander:playlist:57fCqeT985hMUNrAizJNCh