playlists:
 chicago-riot-fest-2015-saturday:
   slug: chicago-riot-fest-2015-sunday
   name: Chicago Riot Fest 2015 Sunday
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL the weekend of September 11-13 2015.
             {{ playlist_title }} will feature headliners of <em>Modest Mouse</em>, <em>The Prodigy</em>, <em>Snoop Dogg</em>, <em>Damian Marley</em>, and <em>Tenacious D</em>.
          </p>
   image: /images/playlists/chicago-riot-fest-2015-sunday.png
   spotify_uri: spotify:user:easander:playlist:13jQdWiVBi1NEh1cVCpLJD
 chicago-riot-fest-2015-friday:
   slug: chicago-riot-fest-2015-friday
   name: Chicago Riot Fest 2015 Friday
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL the weekend of September 11-13 2015.
             {{ playlist_title }} will feature headliners of <em>No Doubt</em>, <em>Faith No More</em>, <em>Motörhead</em>, <em>Ice Cube</em>, and <em>Alkaline Trio</em>.
          </p>
   image: /images/playlists/chicago-riot-fest-2015-friday.jpg
   spotify_uri: spotify:user:easander:playlist:7BDifAdjeF0sEJbkEgKrI6
 denver-riot-fest-and-rodeo-2015:
   slug: denver-riot-fest-and-rodeo-2015
   name: Denver Riot Fest and Rodeo 2015
   content: >
          <p>
             <a href="http://riotfest.org/denver/" target="_blank">{{ playlist_title }}</a> will be held at National Western Complex (4655 Humboldt St, Denver CO) the weekend of August 28th, 29th, and 30th 2015.
             {{ playlist_title }} will feature headliners of <em>System of a Down</em>, <em>Iggy Pop</em>, <em>Modest Mouse</em>, <em>Pixies</em>, <em>The Prodigy</em>, and <em>Snoop Dogg</em>.
          </p>
   image: /images/playlists/denver-riot-fest-2015.jpg
   spotify_uri: spotify:user:easander:playlist:3oTi3mzcodmZoE8yLsLbLk
 toronto-riot-fest-2015:
   slug: toronto-riot-fest-2015
   name: Toronto Riot Fest 2015
   content: >
          <p>
             <a href="http://riotfest.org/toronto/" target="_blank">{{ playlist_title }}</a> will be held in Downsview Park (35 Carl Hall Rd) Toronto, ON September 19th and 20th 2015.
             {{ playlist_title }} will feature headliners of <em>Alexisonfire</em>, <em>Weezer</em> (playing Pinkerton and the Blue Album), <em>The Prodigy</em>, and <em>Wu-Tang Clan</em>.
             <em>Rancid</em> will also be playing ...And Out Come The Wolves.
          </p>
   image: /images/playlists/toronto-riot-fest-2015.jpg
   spotify_uri: spotify:user:easander:playlist:4rGvL29N07RVrgKCVU5akZ
 chicago-riot-fest-2015:
   slug: chicago-riot-fest-2015
   name: Chicago Riot Fest 2015
   content: >
          <p>
             <a href="http://riotfest.org/chicago/" target="_blank">{{ playlist_title }}</a> to be held in Douglas Park, Chicago IL the weekend of September 11-13 2015.
             {{ playlist_title }} will feature headliners of <em>No Doubt</em>, <em>System of a Down</em>, <em>Modest Mouse</em>, <em>Faith No More</em>, and <em>The Prodigy</em>.
             <em>Rancid</em> will also be playing ...And Out Come The Wolves in its entirety.
             <br /><br />
             <em>Update: System of a Down, The Prodigy, 88 Fingers Louie, and Chef'special added to Riot Fest 2015!</em>
          </p>
   image: /images/playlists/chicago-riot-fest-2015.jpg
   spotify_uri: spotify:user:easander:playlist:3jxmUYBHHYuZEyAaXKF76K
 chicago-riot-fest-2014:
   slug: chicago-riot-fest-2014
   name: Chicago Riot Fest 2014
   content: ''
   image: /images/playlists/chicago-riot-fest-2014.jpg
   spotify_uri: spotify:user:easander:playlist:3fl2SYC95YZL9Lsmm3bXl4
 summerland-tour-2014:
   slug: summerland-tour-2014
   name: Summerland Tour 2014
   content: ''
   image: /images/playlists/summerland-tour-2014.jpg
   spotify_uri: spotify:user:easander:playlist:57fCqeT985hMUNrAizJNCh